version: '3.8'
services:
  sql_server_container:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "!MajdSaeed2002"
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  api:
    build:
      context: ./YourApiName
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sql_server_container
